In [ ]:
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "install", "keplergl"])

In [1]:
import keplergl

keplergl.__version__

'0.3.2'

In [2]:
# Load an empty map
from keplergl import KeplerGl
map_1 = KeplerGl()
map_1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl()

In [3]:
import pandas as pd
df = pd.read_csv('hex-data.csv')
df

             hex_id  value  is_true  float_value  empty           time
0   89283082c2fffff     64     True         64.1    NaN  11/1/17 11:00
1   8928308288fffff     73     True         73.1    NaN  11/1/17 11:00
2   89283082c07ffff     65     True         65.1    NaN  11/1/17 11:00
3   89283082817ffff     74     True         74.1    NaN  11/1/17 11:00
4   89283082c3bffff     66     True         66.1    NaN  11/1/17 11:00
..              ...    ...      ...          ...    ...            ...
83  8928309537bffff      4     True          4.1    NaN  11/1/17 11:00
84  89283082d93ffff      6     True          6.1    NaN  11/1/17 11:00
85  89283082d73ffff      1     True          1.1    NaN  11/1/17 13:00
86  8928309530bffff      1     True          1.1    NaN  11/1/17 11:00
87  8928309532bffff      1     True          1.1    NaN  11/1/17 11:00

[88 rows x 6 columns]

In [4]:
%run hex_config.py
config

{'version': 'v1',
 'config': {'visState': {'layers': [{'type': 'hexagonId',
     'visualChannels': {'sizeField': {'type': 'integer', 'name': 'value'},
      'coverageField': None,
      'colorScale': 'quantize',
      'coverageScale': 'linear',
      'colorField': {'type': 'integer', 'name': 'value'},
      'sizeScale': 'linear'},
     'config': {'dataId': 'data_1',
      'color': [250, 116, 0],
      'textLabel': {'color': [255, 255, 255],
       'field': None,
       'size': 50,
       'anchor': 'middle',
       'offset': [0, 0]},
      'label': 'H3 Hexagon',
      'isVisible': True,
      'visConfig': {'coverageRange': [0, 1],
       'opacity': 0.8,
       'elevationScale': 5,
       'hi-precision': False,
       'coverage': 1,
       'enable3d': True,
       'sizeRange': [0, 500],
       'colorRange': {'category': 'Uber',
        'type': 'sequential',
        'colors': ['#194266',
         '#355C7D',
         '#63617F',
         '#916681',
         '#C06C84',
         '#D28389',
         '#E59A8F',
         '#F8B195'],
        'reversed': False,
        'name': 'Sunrise 8'}},
      'columns': {'hex_id': 'hex_id'}},
     'id': 'jdys7lp'}],
   'interactionConfig': {'brush': {'enabled': False, 'size': 0.5},
    'tooltip': {'fieldsToShow': {'data_1': ['hex_id', 'value']},
     'enabled': True}},
   'splitMaps': [],
   'layerBlending': 'normal',
   'filters': []},
  'mapState': {'bearing': 2.6192893401015205,
   'dragRotate': True,
   'zoom': 12.32053899007826,
   'longitude': -122.42590232651203,
   'isSplit': False,
   'pitch': 37.374216241015446,
   'latitude': 37.76209132041332},
  'mapStyle': {'mapStyles': {},
   'topLayerGroups': {},
   'styleType': 'dark',
   'visibleLayerGroups': {'building': True,
    'land': True,
    '3d building': False,
    'label': True,
    'water': True,
    'border': False,
    'road': True}}}}

In [5]:
map_2 = KeplerGl(height=400, data={'data_1': df}, config=config)
map_2

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(config={'version': 'v1', 'config': {'visState': {'layers': [{'type': 'hexagonId', 'visualChannels': {â€¦

In [ ]:
# DataFrame
map_1.add_data(data=df, name='data_1')

# CSV
with open('hex-data.csv', 'r') as f:
    csvData = f.read()
map_1.add_data(data=csvData, name='data_2')

In [7]:
# GeoJSON as string
with open('sf_zip_geo.json', 'r') as f:
    geojson = f.read()

map_1.add_data(data=geojson, name='geojson')
map_1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [], 'interactionConfig': {'â€¦

In [8]:
map_1.data.keys()

dict_keys(['geojson'])

In [10]:
feature = {
    "type": "Feature",
    "properties": {"name": "Coors Field"},
    "geometry": {"type": "Point", "coordinates": [-104.99404, 39.75621]}
}

featureCollection = {
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
        "properties": {"prop0": "value0"}
    }]
}

map_1.add_data(data=feature, name="feature")
map_1.add_data(data=featureCollection, name="feature_collection")
map_1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [], 'interactionConfig': {'â€¦

In [12]:
import json

# GeoJson Feature geometry
geometryString = {
    'type': 'Polygon',
    'coordinates': [[[-74.158491,40.835947],[-74.148473,40.834522],[-74.142598,40.833128],[-74.151923,40.832074],[-74.158491,40.835947]]]
}

# create json string
json_str = json.dumps(geometryString)

# create data frame
df_with_geometry = pd.DataFrame({
    'id': [1],
    'geometry_string': [json_str]
})

# add to map
map_1.add_data(df_with_geometry, "df_with_geometry")
map_1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [], 'interactionConfig': {'â€¦

In [16]:
w1 = KeplerGl()

df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})

w1.add_data(data=df, name='cities')
w1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'cities': {'index': [0, 1, 2, 3, 4], 'columns': ['City', 'Latitude', 'Longitude'], 'data': [['Bâ€¦

In [21]:
import geopandas
url = 'http://eric.clst.org/assets/wiki/uploads/Stuff/gz_2010_us_040_00_500k.json'
country_gdf = geopandas.read_file(url)
country_gdf

,GEO_ID,STATE,NAME,LSAD,CENSUSAREA,geometry
0,0400000US23,23,Maine,,30842.923,"MULTIPOLYGON (((-67.61976 44.51975, -67.61541 ..."
1,0400000US25,25,Massachusetts,,7800.058,"MULTIPOLYGON (((-70.83204 41.60650, -70.82373 ..."
2,0400000US26,26,Michigan,,56538.901,"MULTIPOLYGON (((-88.68443 48.11579, -88.67563 ..."
3,0400000US30,30,Montana,,145545.801,"POLYGON ((-104.05770 44.99743, -104.25015 44.9..."
4,0400000US32,32,Nevada,,109781.180,"POLYGON ((-114.05060 37.00040, -114.04999 36.9..."
5,0400000US34,34,New Jersey,,7354.220,"POLYGON ((-75.52684 39.65571, -75.52634 39.656..."
6,0400000US36,36,New York,,47126.399,"MULTIPOLYGON (((-71.94356 41.28668, -71.92680 ..."
7,0400000US37,37,North Carolina,,48617.905,"MULTIPOLYGON (((-82.60288 36.03983, -82.60074 ..."
8,0400000US39,39,Ohio,,40860.694,"MULTIPOLYGON (((-82.81349 41.72347, -82.81049 ..."
9,0400000US42,42,Pennsylvania,,44742.703,"POLYGON ((-75.41504 39.80179, -75.42804 39.809..."
10,0400000US44,44,Rhode Island,,1033.814,"MULTIPOLYGON (((-71.28157 41.64821, -71.27817 ..."
11,0400000US47,47,Tennessee,,41234.896,"POLYGON ((-81.67754 36.58812, -81.68014 36.585..."
12,0400000US48,48,Texas,,261231.711,"MULTIPOLYGON (((-97.13436 27.89633, -97.13360 ..."
13,0400000US49,49,Utah,,82169.620,"POLYGON ((-114.05060 37.00040, -114.05175 37.0..."
14,0400000US53,53,Washington,,66455.521,"MULTIPOLYGON (((-123.09055 49.00198, -123.0353..."
15,0400000US55,55,Wisconsin,,54157.805,"MULTIPOLYGON (((-90.45525 47.02400, -90.45713 ..."
16,0400000US72,72,Puerto Rico,,3423.775,"MULTIPOLYGON (((-65.58733 18.38199, -65.59122 ..."
17,0400000US24,24,Maryland,,9707.241,"MULTIPOLYGON (((-76.07147 38.20350, -76.04879 ..."
18,0400000US01,01,Alabama,,50645.326,"MULTIPOLYGON (((-85.00237 31.00068, -85.02411 ..."
19,0400000US02,02,Alaska,,570640.950,"MULTIPOLYGON (((-164.97620 54.13459, -164.9377..."
20,0400000US04,04,Arizona,,113594.084,"POLYGON ((-109.04522 36.99908, -109.04524 36.9..."
21,0400000US05,05,Arkansas,,52035.477,"POLYGON ((-94.55929 36.49950, -94.51948 36.499..."
22,0400000US06,06,California,,155779.220,"MULTIPOLYGON (((-122.44632 37.86105, -122.4385..."
23,0400000US08,08,Colorado,,103641.888,"POLYGON ((-102.04224 36.99308, -102.05450 36.9..."
24,0400000US09,09,Connecticut,,4842.355,"MULTIPOLYGON (((-71.85957 41.32240, -71.86823 ..."
25,0400000US10,10,Delaware,,1948.543,"MULTIPOLYGON (((-75.55945 39.62981, -75.55910 ..."
26,0400000US11,11,District of Columbia,,61.048,"POLYGON ((-77.03860 38.79151, -77.03890 38.800..."
27,0400000US12,12,Florida,,53624.759,"MULTIPOLYGON (((-85.15641 29.67963, -85.13740 ..."
28,0400000US13,13,Georgia,,57513.485,"POLYGON ((-81.44412 30.70971, -81.44872 30.709..."
29,0400000US15,15,Hawaii,,6422.628,"MULTIPOLYGON (((-171.73761 25.79210, -171.7223..."
30,0400000US16,16,Idaho,,82643.117,"POLYGON ((-111.04669 42.00157, -111.41587 42.0..."
31,0400000US17,17,Illinois,,55518.930,"POLYGON ((-87.53233 39.99778, -87.53254 39.987..."
32,0400000US18,18,Indiana,,35826.109,"POLYGON ((-88.02803 37.79922, -88.02938 37.803..."
33,0400000US19,19,Iowa,,55857.130,"POLYGON ((-95.76565 40.58521, -95.75889 40.588..."
34,0400000US20,20,Kansas,,81758.717,"POLYGON ((-94.61808 36.99813, -94.62522 36.998..."
35,0400000US21,21,Kentucky,,39486.338,"MULTIPOLYGON (((-83.67541 36.60081, -83.67561 ..."
36,0400000US22,22,Louisiana,,43203.905,"MULTIPOLYGON (((-88.86507 29.75271, -88.88975 ..."
37,0400000US27,27,Minnesota,,79626.743,"POLYGON ((-91.37161 43.50095, -91.37695 43.500..."
38,0400000US28,28,Mississippi,,46923.274,"MULTIPOLYGON (((-88.71072 30.25080, -88.65680 ..."
39,0400000US29,29,Missouri,,68741.522,"POLYGON ((-89.53910 36.49820, -89.53452 36.491..."
40,0400000US31,31,Nebraska,,76824.171,"POLYGON ((-95.76565 40.58521, -95.76853 40.583..."
41,0400000US33,33,New Hampshire,,8952.651,"MULTIPOLYGON (((-72.45852 42.72685, -72.45849 ..."
42,0400000US35,35,New Mexico,,121298.148,"POLYGON ((-109.05004 31.33250, -109.05017 31.4..."
43,0400000US38,38,North Dakota,,69000.798,"POLYGON ((-96.56328 45.93524, -96.57690 45.935..."
44,0400000US40,40,Oklahoma,,68594.921,"POLYGON ((-94.61792 36.49941, -94.61531 36.484..."
45,0400000US41,41,Oregon,,95988.013,"POLYGON ((-117.22007 44.30138, -117.22245 44.2..."
46,0400000US45,45,South Carolina,,30060.696,"POLYGON ((-78.54109 33.85111, -78.55394 33.847..."
47,0400000US46,46,South Dakota,,75811.000,"POLYGON ((-96.44341 42.48949, -96.45971 42.486..."
48,0400000US50,50,Vermont,,9216.657,"POLYGON ((-72.04008 44.15575, -72.04271 44.152..."
49,0400000US51,51,Virginia,,39490.086,"MULTIPOLYGON (((-76.04653 37.95359, -76.04169 ..."
50,0400000US54,54,West Virginia,,24038.210,"POLYGON ((-81.96830 37.53780, -81.96540 37.541..."
51,0400000US56,56,Wyoming,,97093.141,"POLYGON ((-109.05008 41.00066, -109.17368 41.0..."

In [22]:
w1.add_data(data=country_gdf, name="state")
w1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [], 'interactionConfig': {'â€¦

In [23]:
# WKT
wkt_str = 'POLYGON ((-74.158491 40.835947, -74.130031 40.819962, -74.148818 40.830916, -74.151923 40.832074, -74.158491 40.835947))'

df_w_wkt = pd.DataFrame({
    'id': [1],
    'wkt_string': [wkt_str]
})

map_1.add_data(df_w_wkt, "df_w_wkt")
map_1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [], 'interactionConfig': {'â€¦